- name: Find processes running on hosts
  hosts: k8s
  
  vars: 
    output_file: "processes.txt"
  tasks:
  - name: Read processes from file
    set_fact:
      vms: "{{ lookup('file', 'vms.txt') }}"

  - name: Search for hosts running processes
    raw: ps -ef |grep -i {{ item }}|grep -v grep
    register: process_output
    loop: "{{ vms.splitlines() }}"
    ignore_errors: yes
  # - name: Register process and host
  #   set_fact:
  #     running_processes: "{{item.stdout.split()[5]}} : {{ansible_hostname}} - {{item.stdout.split()[0] }}"
  #   with_items: "{{ process_output[loop.index0] }}"
  #   when: item.rc == 0   
  # - name: Save output to file
  #   local_action: copy  content="{{running_processes.results[loop.index0]}}" dest="{{ item }}_processes.txt"
  #   loop: "{{ vms.splitlines() }}"
  - name: Save process and hostname
    local_action:
      module: lineinfile
      path: "{{ item }}.txt"
      line: "{{ inventory_hostname }}:{{ process_output.pid }}"
    with_items: "{{ vms.splitlines() }}"